[package]
name = "runners-desktop"
version = "0.1.0"
edition = "2021"

[lib]
name = "runners_desktop"

[dependencies]
panpan = { path = "../../panpan" }
glow = "0.16.0"
winit = "0.30"
glutin = "0.32"
glutin-winit = "0.5"
raw-window-handle = "0.6"
