[package]
name = "demo_game_android"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
panpan = { path = "../../../panpan" }
demo_game = { path = "../../../examples/demo_game" }
glow = "0.16.0"

[profile.release]
opt-level = 3
lto = true
