[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-lEGL", "-C", "link-arg=-lGLESv2", "-C", "link-arg=-llog"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-arg=-lEGL", "-C", "link-arg=-lGLESv2", "-C", "link-arg=-llog"]

[target.i686-linux-android]
rustflags = ["-C", "link-arg=-lEGL", "-C", "link-arg=-lGLESv2", "-C", "link-arg=-llog"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-arg=-lEGL", "-C", "link-arg=-lGLESv2", "-C", "link-arg=-llog"]
