[build]
target = "aarch64-linux-android"

[target.aarch64-linux-android]
linker = "aarch64-linux-android-clang"
rustflags = ["-C", "link-arg=-lEGL", "-C", "link-arg=-lGLESv2", "-C", "link-arg=-llog"]

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi-clang"
rustflags = ["-C", "link-arg=-lEGL", "-C", "link-arg=-lGLESv2", "-C", "link-arg=-llog"]
